// Generated by `velora make:pwa`. Caches the Flutter app shell and velora_db's
// WASM assets so the app works offline. Flutter no longer ships a default
// service worker (flutter/flutter#156910), so Velora provides this one.
//
// Bump CACHE (e.g. v1 -> v2) to force every client to discard the old cache
// on the next load -- useful if a deploy ever appears stale.
const CACHE = 'velora-app-shell-v1';

self.addEventListener('install', (event) => {
  // Activate this worker as soon as it finishes installing, without waiting
  // for existing tabs to close.
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // Drop caches left behind by older CACHE versions of this worker.
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return; // never cache writes (API calls etc.)

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // only same-origin assets

  // Navigations: network-first, so a fresh deploy is served when online and
  // the cached shell (index.html) is served when offline.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      try {
        const fresh = await fetch(request);
        cache.put(request, fresh.clone());
        return fresh;
      } catch (_) {
        return (await cache.match(request)) ||
            (await cache.match('index.html')) ||
            Response.error();
      }
    })());
    return;
  }

  // Everything else same-origin (main.dart.js, canvaskit, fonts, sqlite3.wasm,
  // drift_worker.dart.js, ...): stale-while-revalidate -- serve from cache
  // instantly, refresh the cache in the background.
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(request);
    const network = fetch(request).then((response) => {
      if (response && response.status === 200) cache.put(request, response.clone());
      return response;
    }).catch(() => cached);
    return cached || network;
  })());
});
